### ISSUE TITLE
Mapping the GSA domain ecosystem

### ISSUE THREAD

**Issue by quarterback** [18F/osc-website-pa#14]
GSA's domain ecosystem is vast and confusing. There is not clarity around who owns what, where it belongs, and ultimately, which parts of the ecosystem are within the scope of this project versus which ones are not. Charting towards mapping the ecosystem would give the partners an opportunity to see how vast it is.

### This task is done when...
 - [x] Explore the GSA domain ecosystem
 - [x] Represent that map in a visual form
- [x] Share the ecosystem map

**Comment by austinhernandez** [comment]
- [Here is the Google doc with a list of FAS, PBS, and OGP owned sites.](https://docs.google.com/spreadsheets/d/1Uir6OlubW9w0xR9k9_qazP59Ayqd8xglSpNFxxXngm4/edit#gid=1884845259)

- [Here is the Mural where we will prioritize sites, journeys, or groups within GSA.](https://app.mural.co/t/gsa6/m/gsa6/1540312474275/1dd588f7e59ef5798e50c474216b7a4b2a192fcd)

**Comment by quarterback** [comment]
Started doing heuristic evaluation of GSA sites.

**Comment by quarterback** [comment]
Closing this based on current progress, can create a successor issue that better captures current state if needed.
