### ISSUE TITLE
OSC architecture models deck

### ISSUE THREAD

**Issue by quarterback** [18F/osc-website-pa#31]
After @tbaxter-18f is able to make the changes he wants inside the doc, we'll deploy @austinhernandez for visual improvements to it and @durland18F / @quarterback for content. 

Deck is linked in Slack channel.

**Comment by tbaxter-18f** [comment]
Deck is here: https://docs.google.com/presentation/d/1V4a-n3TST1e0pOiD_nIHVwwU9XoJlSgVU8VsybyCB6g/edit#slide=id.g45fa14a0cb_0_9

I'm ready to hand off to @austinhernandez and @durland18F for design and content improvements.

**Comment by quarterback** [comment]
Deck presented.

**Comment by tbaxter-18f** [comment]
Resolution: Agreement to pursue option 3, the API-driven model.
