### ISSUE TITLE
Audit APIs in the supplier journey

### ISSUE THREAD

**Issue by quarterback** [18F/osc-website-pa#34]

**Comment by tbaxter-18f** [comment]
@quarterback In your opinion, does https://docs.google.com/spreadsheets/d/1tI5rAR4NL5MjByx3r-6EZYJo7cLEJquuiOw6iOUykw0/edit#gid=0 fulfill this?

**Comment by quarterback** [comment]
@tbaxter-18f Absolutely! Will close.
