### ISSUE TITLE
Resolve USWDS loading issues

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/osc-website-pa#47]
The USWDS files aren't loading correctly locally. This may be due to them 404-ing, not being included in the base templates, or we need some changes in the base templates. We're not sure which is the issue yet.

### This task is done when...
 - [ ] USWDS assets load correctly and are reflected on the page.

**Comment by fureigh** [comment]
@line47 Mind if I take a look at this one tomorrow?

**Comment by line47** [comment]
I followed the **1. Use the pre-compiled USWDS library** instruction here https://www.drupal.org/project/uswds where you are asked to download a zip file and rename it "assets" and place the folder inside your subtheme folder: `assets/css/uswds.css` and it seems mine is half working

**Comment by fureigh** [comment]
@line47 Cool. Which half? And did you make any other changes inside the `uswds` directory?
