### ISSUE TITLE
Scoping viability of Drupal style assets

### ISSUE THREAD

**Issue by quarterback** [18F/osc-website-pa#83]
We're hoping to share any of the USWDS styles & theme developed in this project locally publicly if possible. Ultimately, we need to know what's salvageable from what's in the development repo, as we're not sure right now and would like to be able to communicate that to the partner.

Right now, we're not sure if anything can be shared and would just like to know what condition things here are in, whether there's anything useful and if not, where it's been left. 

### This task is done when...
 - [ ] Scope the viability of our Drupal repo -- what can we salvage?
 - [ ] Identify what's shareable with wider Drupal community

**Comment by tbaxter-18f** [comment]
Ron, can we clarify a bit about what the partner would like to see delivered?

**Comment by quarterback** [comment]
The partner hoped for a working prototype site. But in the absence of that, being able to salvage anything in this repo -- Drupal styles and theme, etc. - would be very helpful. We'd like someone to help us understand what's usable, as it's never been made clear.

**Comment by ominina** [comment]
@quarterback @tbaxter-18f let me know the level of effort/time you think this is going to take

**Comment by pburkholder** [comment]
The work for the OSC Drupal prototype has been picked up and folded into the example at https://github.com/18f/cf-ex-drupal8, and that includes the USWDS styles. So having that working again in the OSC prototyping org is only a few hours of effort. That prototype would include:

- local development environment with docker-compose
- a working environment in cloud.gov with database and S3 backend
- a workflow from porting code/configuration from local dev environment to cloud.gov

That's anywhere from 2 to 16 hours of work depending on 
- whether anything needs to be preserved form the current environment
- what issues we'd run into to brand that as "OSC"
- the current state of documentation on the upstream cf-ex-drupal8 project (the project has been active with contributions from @fureigh and @lindsayyoung and myself, so I think it's in pretty good shape).

If they want the prototype to include CI/CD with CircleCI, that's another couple of days of work.

**Comment by quarterback** [comment]
@pburkholder Let's do it. The CircleCI implementation probably isn't needed at this point.

**Comment by fureigh** [comment]
Thanks for picking this up, @pburkholder. To extract the branding that was implemented, I suggest: 1) cherry-picking the most recent commits from https://github.com/18F/osc-website-pa/tree/add-initial-header-footer-page and 2) replacing `web/sites/custom/your_uswds_subtheme` with the most recent version of the `osc` theme that's in that branch.

**Comment by tbaxter-18f** [comment]
Just curious, are we going with USWDS 1.x or 2.x?

**Comment by fureigh** [comment]
As-is, it’s USWDS 1.0; USWDS 2.0 was released well after development was
paused.

If there’s budget and appetite, we could assess what it’d take to change it
to 2.0... an alpha version of the USWDS Drupal base theme was released two
weeks ago. That would constitute new development, though.
-- 
---
Fureigh
my.pronoun.is/they
Engineering Supervisor, 18F
Lead, 10x Federal Grantee Reporting Project
rhys.fureigh@gsa.gov
C: 415 806 9604 <4158069604> <4158069604>

**Comment by ominina** [comment]
@quarterback I believe we are sticking with 1.0 yeah? We also dont have budget for new development

**Comment by fureigh** [comment]
Connecting the dots on this: I posted a pull request [here](https://github.com/18F/osc-website-pa/pull/84) with proposed next steps.

**Comment by quarterback** [comment]
This is done.
